git clone https://github.com/ljr1981/bem
git clone https://github.com/ljr1981/css
git clone https://github.com/ljr1981/eav
git clone https://github.com/ljr1981/ecf_generator
git clone https://github.com/ljr1981/ecfwingen
git clone https://github.com/EiffelWebFramework/EWF/
git clone https://github.com/ljr1981/ewf_ext
git clone https://github.com/ljr1981/Framework
git clone https://github.com/ljr1981/github_helper
git clone https://github.com/ljr1981/graphviz
git clone https://github.com/ljr1981/html
git clone https://github.com/ljr1981/integrator
git clone https://github.com/ljr1981/java_script
git clone https://github.com/ljr1981/jqmobile
git clone https://github.com/ljr1981/json_ext
git clone https://github.com/ljr1981/locking
git clone https://github.com/ljr1981/logging_extension
git clone https://github.com/ljr1981/moon_tracks
git clone https://github.com/ljr1981/moonshot
git clone https://github.com/ljr1981/permission
git clone https://github.com/ljr1981/pub_sub
git clone https://github.com/ljr1981/randomizer
git clone https://github.com/ljr1981/reporting
git clone https://github.com/ljr1981/state_machine
git clone https://github.com/ljr1981/test_extension
git clone https://github.com/ljr1981/validation
git clone https://github.com/ljr1981/web_components
git clone https://github.com/ljr1981/website_x
